# Q1. Total revenue generated by male vs female customers
select sum(purchase_amount) as total_revenue, gender
from customer
group by gender;

# Q2. Which customers used a discount and still spent higher than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied='Yes' and purchase_amount > (select avg(purchase_amount) from customer);

# Q3. Top 5 products with highest average review rating
select item_purchased, round(avg(review_rating),2) as avg_review_rating from customer
group by item_purchased
order by avg(review_rating) desc
limit 5; 

# Q4. Compare average purchase amount between Standard & Express shipping
select round(avg(purchase_amount),2) as avg_purchase_amount, shipping_type
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

# Q5. Compare average spend & total revenue b/w subscribers & non-subscribers
select avg(purchase_amount) as avg_spend,
	   sum(purchase_amount) as total_revenue,
       count(customer_id) as total_customers,
       subscription_status
from customer
group by subscription_status;

# Q6. Which 5 products have the highest % of purchases with discount applied?
select round((100*sum(case
		when discount_applied='YES' then 1 else 0 end)/count(*)),2) as discount_rate,
	   item_purchased
from customer
group by item_purchased
order by discount_rate desc
limit 5;

# Q7. Segement into - New, Returning & Loyal based on their total no. of previous purchases
# and show the count of each segment
with cte1 as (
select customer_id, previous_purchases,
		case 
			when previous_purchases = 1 then 'New'
			when previous_purchases between 2 and 10 then 'Returning'
			else 'Loyal'
		end as customer_segment
from customer)
select customer_segment, count(*) as no_of_customers
from cte1
group by customer_segment;

# Q8. Top 3 most purchased products in each category
with cte1 as (
select item_purchased, category, count(*) as total_orders,
row_number() over(partition by category order by count(*) desc) as item_rank
from customer
group by category, item_purchased)
select * 
from cte1
where item_rank <= 3
group by subscription_status; 

# Q9. The customers who are repeat buyers (more than 5 prev. purchases) also likely to subscribe?
select subscription_status, count(*) as buyers
from customer
where previous_purchases > 5
group by subscription_status;

# Q10. Revenue contribution of each age group
select sum(purchase_amount) as revenue_contribution, age_group
from customer
group by age_group
order by sum(purchase_amount) desc;









